config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get 'getting/index'

  devise_for :bloguers, controllers: {sessions: 'bloguers/sessions', registrations: 'bloguers/registrations'}

  root 'home#index'
  get 'quieres-ser-un-bloguer', to: 'getting#index', as: 'getting'
  get 'bloguers/:id', to: 'bloguers#show', as: 'bloguer'
  get 'bloguer/:id', to: 'bloguers#edit', as: 'perfil'
  put 'bloguer/:id', to: 'bloguers#update'
  get 'bloguers', to: 'bloguers#index'
  resources :posts

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #desarrollo
    #@bloguers = Bloguer.order("RANDOM()").limit(3)
    #production
    @bloguers = Bloguer.limit(5).order("RAND()")
    @posts = Post.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container-fluid home_head">
  <div class="row">
    <div class="col-md-2 col-sm-2 col-xs-2">
      <%= image_tag("logo.png", class: "logo") %>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-6">
      <nav class="nav_home">
        <ul>
          <% if bloguer_signed_in? %>
              <li>
                <%= link_to('Logout', destroy_bloguer_session_path, :method => :delete) %>
              </li>
              <li>
                <%= link_to('Perfil', perfil_path(current_bloguer))%>
              </li>
              <li>
                <%= link_to('Mis Posts', posts_path) %>
              </li>
          <% else %>
              <li>
                <%= link_to('Login', new_bloguer_session_path)  %>
              </li>
              <li>
                <%= link_to("Quieres ser un Bloguer?", getting_path) %>
              </li>
          <% end %>

        </ul>
      </nav>
    </div>
  </div>
  <div class="row text_white">
    <div class="col-md-6 text_main text_center col-sm-6 col-xs-6">
      <strong class="t1 tfw">
        A
        </strong>
        <strong class="t2">
          qui
        </strong>
        <strong class="t3">
          encontraras
        </strong>
        <strong class="t2">
          el mejor
        </strong>
        <strong class="t3">contenido</strong>
        <strong class="t1 tfw">...!</strong>
    </div>
  </div>
</div>
<!-- posts container -->
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 col-sm-2 col-xs-2">
      <!--publicidad  -->
      <!-- home lateral der new -->
      <ins class="adsbygoogle"
           style="display:block"
           data-ad-client="ca-pub-8271065065744793"
           data-ad-slot="6159889461"
           data-ad-format="auto"></ins>

    </div>
    <div class="col-md-8 col-sm-8 col-xs-8">
      <div class="row">
        <!--  bloguers -->
        <h2 class="text_orange">
          Bloguers
        </h2>
        <div class="under_blue"></div>
        <!--perfil bloguer  -->
        <div class="row text_center" style="height: 160px">
          <% @bloguers.each do |bloguer| %>
        <div class="col-md-3 col-sm-3 col-xs-3">
          <div class="row">
            <% if bloguer.avatar_file_name == nil %>
                <a href="<%= bloguer_path(bloguer) %>"><%= image_tag("perfil.jpg", class: "home_perfil") %></a>
                <%else%>
                <a href="<%= bloguer_path(bloguer) %>"><%= image_tag bloguer.avatar.url(:thumb), class: "home_perfil" %></a>
                <%end%>
            <div class="row">

              <h4><%= bloguer.name %> <%= bloguer.lastname %></h4>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6">
              <strong>

              </strong>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6">
              <strong>
                <% %>
              </strong>
            </div>
          </div>
        </div>
        <%end%>
          <div class="col-md-3 col-sm-3 col-xs-3">
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <a class="bloguer_view" href="<%= bloguers_path %>"><i class="fa fa-plus-circle"></i></a>
              </div>
            </div>
          </div>
        </div>
        <!--end perfil bloguer  -->
      </div>
      <!--end bloguers  -->
      <!-- Posts -->
      <div class="row">
        <h2 class="text_orange">
          Ultimos posts
        </h2>
        <div class="under_blue"></div>
        <div class="row text_center">
          <% @posts.each do |post| %>
        <div class="col-md-3 col-md-offset-1 col-sm-3 col-sm-offset-1 col-xs-3 col-xs-offset-1 post" style="margin-bottom: 20px">
          <div class="home_before_img"></div>
          <a href="<%= post_path(post) %>"><%= image_tag post.picture.url(:medium), class: "home_post_img" %></a>
          <div class="row">
            <h3>
              <%= post.title %>
            </h3>
            <div class="col-md-6 col-sm-6 col-xs-6">

            </div>
            <div class="col-md-6 col-sm-6 col-xs-6">
              <strong>
                <%= post.impressionist_count %> <i class="fa fa-eye"></i>
              </strong>
            </div>
          </div>
        </div>
        <%end%>
      </div>
      </div>
    </div>
    <div class="col-md-2 col-sm-2 col-xs-2">
      <!-- publicidad -->
      <!-- home lateral der new -->
      <ins class="adsbygoogle"
           style="display:block"
           data-ad-client="ca-pub-8271065065744793"
           data-ad-slot="6159889461"
           data-ad-format="auto"></ins>

    </div>
  </div>
</div>
<%= render "layouts/footer" %>