config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get 'getting/index'

  devise_for :bloguers, controllers: {sessions: 'bloguers/sessions', registrations: 'bloguers/registrations'}

  root 'home#index'
  get 'quieres-ser-un-bloguer', to: 'getting#index', as: 'getting'
  get 'bloguers/:id', to: 'bloguers#show', as: 'bloguer'
  get 'bloguer/:id', to: 'bloguers#edit', as: 'perfil'
  put 'bloguer/:id', to: 'bloguers#update'
  get 'bloguers', to: 'bloguers#index'
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :bloguer
  include Bootsy::Container
  is_impressionable
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_bloguer!, :except => [:show]
  impressionist actions: [:show]
  layout "post", :only => :show

  def index
    bloguer = current_bloguer.id
    bloguerPost = Bloguer.where(id: bloguer)
    @posts = Post.where(bloguer_id: bloguerPost).order('id DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.bloguer_id = current_bloguer.id
    if @post.save
      redirect_to posts_url
    end
  end

  def image
    @image = Post.new(post_params)
    @image.bloguer_id = current_bloguer.id
    if @image.save
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    impressionist(@post)
    @post.impressionist_count
    #develoment
    #@aleatorio = Post.order("RANDOM()").limit(4)
    #production
    @aleatorio = Post.limit(5).order("RAND()")
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to(@post)
    else

    end
  end
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_url
    else

    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :bloguer_id, :view, :picture, :bootsy_image_gallery_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<%= render "layouts/nav_blog_perfil" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <div class="row">
        <div class="col-md-12">
          <nav>
            <ul>
              <li>
                <%= link_to content_tag(:i, " Dashboard", class: 'fa fa-eye'), posts_path %>
              </li>
              <li>
                <%= link_to content_tag(:i, " Perfil", class: 'fa fa-eye'), edit_bloguer_registration_path %>
              </li>
              <li>
                <%= link_to content_tag(:i, " New Post", class: 'fa fa-eye'), new_post_path %>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <%= form_for @post, url: {action: "update"}, html: {multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-10">
              <h1>Titulo del Post</h1>
            </div>
            <div class="col-md-2">
              <%= f.submit "Guardar", class: "btn btn-success btn-lg", style: "margin-top: 10%" %>
            </div>
            <div class="col-md-12">
              <%= f.text_field :title, class: "post_title" %>
            </div>
            <div class="col-md-12">
              <%= f.bootsy_area :body, class: "form-control bootsy_text_area", style:"" %>
            </div>
          </div>
          </div>
          <div class="col-md-2">
            <div class="row">
              <div class="col-md-12">
                <%= image_tag @post.picture.url(:thumb), id: "preview_post", style:"width: 100%; margin-bottom: 20px" %>
                <%= f.file_field :picture, id: "pImage", class:"filestyle", style: "width: 90%;"%>
      <%end%>
      </div>
      </div>
      </div>
      </div>
    </div>

app/views/posts/index.html.erb
<%= render "layouts/nav_blog_perfil" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
        <div class="row">
          <div class="col-md-12">
            <nav>
              <ul>
                <li>

                  <%= link_to content_tag(:i, " Dashboard", class: 'fa fa-eye'), posts_path %>
                </li>
                <li>
                  <%= link_to "new post", new_post_path, :target => "_blank" %>
                </li>
              </ul>
            </nav>
          </div>
        </div>
    </div>
    <div class="col-md-10">
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Imagen</th>
          <th>Titulo</th>
          <th>Fecha creado</th>
          <th>Fecha atualizado</th>
          <th>Visto</th>
          <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        <% @posts.each do |p| %>
            <tr>
              <td><%= image_tag p.picture.url(:thumb) %></td>
              <td style="vertical-align: middle"><%= p.title %></td>
              <td style="vertical-align: middle"><%= p.created_at.strftime('%d-%m-%Y') %></td>
              <td style="vertical-align: middle"><%= p.updated_at.strftime('%d-%m-%Y') %></td>
              <th style="vertical-align: middle"><%= p.impressionist_count %></th>
              <th style="vertical-align: middle">
                <%= link_to content_tag(:i, nil, class: 'fa fa-eye'), p %>
                <%= link_to content_tag(:i, nil, class: 'fa fa-pencil-square-o'), edit_post_path(p) %>
                <%= link_to content_tag(:i, nil, class: 'fa fa-times'), p, method: :delete, data: { confirm: "Desea eliminar?" } %>
              </th>
            </tr>
        <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render "layouts/nav_blog_perfil" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <div class="row">
        <div class="col-md-12">
          <nav>
            <ul>
              <li>
                <%= link_to content_tag(:i, " Dashboard", class: 'fa fa-eye'), posts_path %>
              </li>
              <li>
                <%= link_to content_tag(:i, " Perfil", class: 'fa fa-eye'), edit_bloguer_registration_path %>
              </li>
              <li>
                <%= link_to content_tag(:i, " New Post", class: 'fa fa-eye'), new_post_path %>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <%= form_for @post, url: {action: "create"}, html: { method: :post, multipart: true } do |f| %>
        <div class="row">
          <div class="col-md-10">
            <h1>Titulo del Post</h1>
          </div>
           <div class="col-md-2">
             <%= f.submit "Publicar", class: "btn btn-success btn-lg", style: "margin-top: 10%" %>
           </div>
          <div class="col-md-12">
            <%= f.text_field :title, class: "post_title" %>
          </div>
          <div class="col-md-12">
            <%= f.bootsy_area :body, class: "form-control bootsy_text_area", style:"" %>
          </div>
        </div>
    </div>
    <div class="col-md-2">
      <div class="row">
        <div class="col-md-12">
          <%= image_tag @post.picture.url(:thumb), id: "preview_post", style:"width: 100%; margin-bottom: 20px" %>
              <%= f.file_field :picture, id: "pImage", class:"filestyle", style: "width: 90%;"%>
          <%end%>
        </div>
      </div>
  </div>
</div>
    </div>
<!-- payone  -->
<!-- -->

app/views/posts/show.html.erb
<%= render "layouts/nav_blog_perfil" %>

<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '1031371466877255',
            xfbml      : true,
            version    : 'v2.3'
        });
    };

    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<div id="fb-root"></div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 col-sm-2 col-xs-2">
      <!-- publicidad -->
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <!-- publicidad -->

          <!-- home lateral der new -->
          <ins class="adsbygoogle"
               style="display:block"
               data-ad-client="ca-pub-8271065065744793"
               data-ad-slot="6159889461"
               data-ad-format="auto"></ins>

        </div>
      </div>
    </div>
    <div class="col-md-8 col-sm-8 col-xs-8">
      <!-- content -->
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="row">
            <h1><%= @post.title %></h1>
          </div>
          <div class="row" style="margin-bottom: 100px">
            <div
            class="fb-like"
            data-share="true"
            data-width="450"
            data-show-faces="true">
            </div>
            <%= image_tag @post.picture.url(:medium)%>
          </div>
          <div class="froala-view">
            <%if @post.body.blank? %>
                <%else%>
                <% str=@post.body %>
                <%= CGI.unescapeHTML(str).html_safe %>
            <%end%>
          </div>
        </div>
        <!--post aleatorios -->
        <div class="row">
          <% @aleatorio.each do |a| %>
          <div class="col-md-3 col-sm-3 col-xs-3 post_rand">
            <div class="row text_center">
              <a href="<%= post_path(a) %>"><%= image_tag a.picture.url(:thumb) %></a>
              <div class="col-md-12 col-sm-12 col-xs-12">
                <h5>
                  <%= a.title %>
                </h5>
              </div>
            </div>
          </div>
          <%end%>
        </div>

        <!-- end post -->
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div
          class="fb-like"
          data-share="true"
          data-width="450"
          data-show-faces="true">
          </div>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="fb-comments" data-href="https://www.facebook.com/timeofmadnessblog/post/<%= @post.id %>" data-numposts="5"></div>
        </div>
      </div>
    </div>
    <div class="col-md-2 col-sm-2 col-xs-2">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <!-- publicidad -->
          <!-- home lateral der new -->
          <ins class="adsbygoogle"
               style="display:block"
               data-ad-client="ca-pub-8271065065744793"
               data-ad-slot="6159889461"
               data-ad-format="auto"></ins>


        </div>
      </div>
    </div>
  </div>
</div>

<%= render "layouts/footer" %>